"""driver payments models

Revision ID: 0287018013c8
Revises: d002f43e6850
Create Date: 2025-11-06 05:56:08.994062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0287018013c8'
down_revision: Union[str, Sequence[str], None] = 'd002f43e6850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ach_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_number', sa.String(length=20), nullable=False, comment='Format: YYMM-XXX (e.g., 2510-001)'),
    sa.Column('batch_date', sa.DateTime(timezone=True), nullable=False, comment='When the batch was created'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='Effective entry date for ACH processing'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'NACHA_GENERATED', 'SUBMITTED', 'REVERSED', name='achbatchstatus'), nullable=False),
    sa.Column('total_payments', sa.Integer(), nullable=False, comment='Number of payments in batch'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total dollar amount of batch'),
    sa.Column('nacha_file_path', sa.String(length=500), nullable=True, comment='S3 path to generated NACHA file'),
    sa.Column('nacha_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ach_batches_batch_number'), 'ach_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_ach_batches_is_reversed'), 'ach_batches', ['is_reversed'], unique=False)
    op.create_index(op.f('ix_ach_batches_status'), 'ach_batches', ['status'], unique=False)
    op.create_table('company_bank_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Company name for NACHA file'),
    sa.Column('company_tax_id', sa.String(length=10), nullable=False, comment='Company EIN or tax ID (10 digits)'),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bank_routing_number', sa.String(length=9), nullable=False, comment='9-digit ABA routing number'),
    sa.Column('bank_account_number', sa.String(length=17), nullable=False, comment='Company account number (up to 17 digits)'),
    sa.Column('immediate_origin', sa.String(length=10), nullable=False, comment='10-digit originator ID for NACHA'),
    sa.Column('immediate_destination', sa.String(length=10), nullable=False, comment='10-digit destination routing for NACHA'),
    sa.Column('company_entry_description', sa.String(length=10), nullable=False, comment='Description for NACHA batch (max 10 chars)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_transaction_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_number', sa.String(length=20), nullable=False, comment='Unique receipt identifier (format: RCPT-XXXXX)'),
    sa.Column('week_start_date', sa.Date(), nullable=False, comment='Sunday 00:00 AM - start of payment period'),
    sa.Column('week_end_date', sa.Date(), nullable=False, comment='Saturday 11:59:59 PM - end of payment period'),
    sa.Column('generation_date', sa.DateTime(timezone=True), nullable=False, comment='When this DTR was generated'),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=True),
    sa.Column('credit_card_earnings', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total CURB credit card earnings for the week'),
    sa.Column('lease_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mta_fees_total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Sum of all MTA-related fees'),
    sa.Column('mta_fee_mta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mta_fee_tif', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mta_fee_congestion', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mta_fee_crbt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mta_fee_airport', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ezpass_tolls', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pvb_violations', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tlc_tickets', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('repairs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_loans', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('misc_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_deductions', sa.Numeric(precision=10, scale=2), nullable=False, comment='Sum of all deductions'),
    sa.Column('net_earnings', sa.Numeric(precision=10, scale=2), nullable=False, comment='credit_card_earnings - subtotal_deductions'),
    sa.Column('total_due_to_driver', sa.Numeric(precision=10, scale=2), nullable=False, comment='Final amount owed to driver'),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'PAID', 'VOID', name='dtrstatus'), nullable=False),
    sa.Column('ach_batch_id', sa.Integer(), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True, comment='Manual check number if paid by check'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['ach_batch_id'], ['ach_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'lease_id', 'week_start_date', name='uq_dtr_driver_lease_week')
    )
    op.create_index('idx_dtr_driver_lease', 'driver_transaction_receipts', ['driver_id', 'lease_id'], unique=False)
    op.create_index('idx_dtr_status_payment', 'driver_transaction_receipts', ['status', 'ach_batch_id', 'check_number'], unique=False)
    op.create_index('idx_dtr_week', 'driver_transaction_receipts', ['week_start_date', 'week_end_date'], unique=False)
    op.create_index(op.f('ix_driver_transaction_receipts_ach_batch_id'), 'driver_transaction_receipts', ['ach_batch_id'], unique=False)
    op.create_index(op.f('ix_driver_transaction_receipts_check_number'), 'driver_transaction_receipts', ['check_number'], unique=False)
    op.create_index(op.f('ix_driver_transaction_receipts_driver_id'), 'driver_transaction_receipts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_transaction_receipts_lease_id'), 'driver_transaction_receipts', ['lease_id'], unique=False)
    op.create_index(op.f('ix_driver_transaction_receipts_receipt_number'), 'driver_transaction_receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_driver_transaction_receipts_status'), 'driver_transaction_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_driver_transaction_receipts_week_end_date'), 'driver_transaction_receipts', ['week_end_date'], unique=False)
    op.create_index(op.f('ix_driver_transaction_receipts_week_start_date'), 'driver_transaction_receipts', ['week_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_transaction_receipts_week_start_date'), table_name='driver_transaction_receipts')
    op.drop_index(op.f('ix_driver_transaction_receipts_week_end_date'), table_name='driver_transaction_receipts')
    op.drop_index(op.f('ix_driver_transaction_receipts_status'), table_name='driver_transaction_receipts')
    op.drop_index(op.f('ix_driver_transaction_receipts_receipt_number'), table_name='driver_transaction_receipts')
    op.drop_index(op.f('ix_driver_transaction_receipts_lease_id'), table_name='driver_transaction_receipts')
    op.drop_index(op.f('ix_driver_transaction_receipts_driver_id'), table_name='driver_transaction_receipts')
    op.drop_index(op.f('ix_driver_transaction_receipts_check_number'), table_name='driver_transaction_receipts')
    op.drop_index(op.f('ix_driver_transaction_receipts_ach_batch_id'), table_name='driver_transaction_receipts')
    op.drop_index('idx_dtr_week', table_name='driver_transaction_receipts')
    op.drop_index('idx_dtr_status_payment', table_name='driver_transaction_receipts')
    op.drop_index('idx_dtr_driver_lease', table_name='driver_transaction_receipts')
    op.drop_table('driver_transaction_receipts')
    op.drop_table('company_bank_configuration')
    op.drop_index(op.f('ix_ach_batches_status'), table_name='ach_batches')
    op.drop_index(op.f('ix_ach_batches_is_reversed'), table_name='ach_batches')
    op.drop_index(op.f('ix_ach_batches_batch_number'), table_name='ach_batches')
    op.drop_table('ach_batches')
    # ### end Alembic commands ###
