"""ezpass models

Revision ID: 0c56dff2a32f
Revises: ccec8c3843f5
Create Date: 2025-11-03 08:03:35.629881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c56dff2a32f'
down_revision: Union[str, Sequence[str], None] = 'ccec8c3843f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ezpass_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original name of the uploaded CSV file.'),
    sa.Column('import_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the import process began.'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ezpassimportstatus'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False, comment='Total number of rows in the CSV file.'),
    sa.Column('successful_records', sa.Integer(), nullable=False, comment='Number of records successfully imported.'),
    sa.Column('failed_records', sa.Integer(), nullable=False, comment='Number of records that failed validation.'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ezpass_imports_id'), 'ezpass_imports', ['id'], unique=False)
    op.create_index(op.f('ix_ezpass_imports_status'), 'ezpass_imports', ['status'], unique=False)
    op.create_table('ezpass_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False, comment='Unique Lane Txn ID from the CSV.'),
    sa.Column('tag_or_plate', sa.String(length=100), nullable=False, comment='The tag or plate number from the CSV.'),
    sa.Column('agency', sa.String(length=100), nullable=False, comment='Tolling agency (e.g., MTAB&T).'),
    sa.Column('entry_plaza', sa.String(length=100), nullable=True),
    sa.Column('exit_plaza', sa.String(length=100), nullable=True),
    sa.Column('transaction_datetime', sa.DateTime(timezone=True), nullable=False, comment='The precise date and time of the toll transaction.'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='The cost of the toll.'),
    sa.Column('med_from_csv', sa.String(length=50), nullable=True, comment="The 'MED' column from the CSV, stored for reference."),
    sa.Column('status', sa.Enum('IMPORTED', 'ASSOCIATION_PENDING', 'ASSOCIATION_FAILED', 'ASSOCIATED', 'POSTING_PENDING', 'POSTING_FAILED', 'POSTED_TO_LEDGER', name='ezpasstransactionstatus'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='Stores the reason for an association or posting failure.'),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True, comment='The date the transaction was posted to the ledger.'),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=True),
    sa.Column('lease_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['ezpass_imports.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ezpass_transactions_driver_id'), 'ezpass_transactions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_id'), 'ezpass_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_import_id'), 'ezpass_transactions', ['import_id'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_lease_id'), 'ezpass_transactions', ['lease_id'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_medallion_id'), 'ezpass_transactions', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_status'), 'ezpass_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_tag_or_plate'), 'ezpass_transactions', ['tag_or_plate'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_transaction_datetime'), 'ezpass_transactions', ['transaction_datetime'], unique=False)
    op.create_index(op.f('ix_ezpass_transactions_transaction_id'), 'ezpass_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_ezpass_transactions_vehicle_id'), 'ezpass_transactions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ezpass_transactions_vehicle_id'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_transaction_id'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_transaction_datetime'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_tag_or_plate'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_status'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_medallion_id'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_lease_id'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_import_id'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_id'), table_name='ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_transactions_driver_id'), table_name='ezpass_transactions')
    op.drop_table('ezpass_transactions')
    op.drop_index(op.f('ix_ezpass_imports_status'), table_name='ezpass_imports')
    op.drop_index(op.f('ix_ezpass_imports_id'), table_name='ezpass_imports')
    op.drop_table('ezpass_imports')
    # ### end Alembic commands ###
