"""miscellaneous charges included

Revision ID: 23c143637566
Revises: cbe5de5b8cb2
Create Date: 2025-10-30 13:11:10.793700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c143637566'
down_revision: Union[str, Sequence[str], None] = 'cbe5de5b8cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miscellaneous_charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('expense_id', sa.String(length=50), nullable=False, comment='Unique identifier (ME-YYYY-NNNNNN)'),
    sa.Column('driver_id', sa.Integer(), nullable=False, comment='Driver who is charged'),
    sa.Column('lease_id', sa.Integer(), nullable=False, comment='Active lease at time of charge'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='Vehicle associated with charge'),
    sa.Column('medallion_id', sa.Integer(), nullable=True, comment='Medallion associated with charge'),
    sa.Column('category', sa.Enum('LOST_KEY', 'CLEANING_FEE', 'LATE_RETURN_FEE', 'ADMINISTRATIVE_FEE', 'DAMAGE_FEE', 'DOCUMENT_FEE', 'PROCESSING_FEE', 'PENALTY_FEE', 'INSURANCE_DEDUCTIBLE', 'EQUIPMENT_FEE', 'MISC_CHARGE', 'ADJUSTMENT', name='miscchargecategory'), nullable=False, comment='Type of miscellaneous charge'),
    sa.Column('charge_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount to be charged (positive or negative for credits)'),
    sa.Column('charge_date', sa.DateTime(), nullable=False, comment='Date when charge was incurred'),
    sa.Column('payment_period_start', sa.DateTime(), nullable=False, comment='Start of payment week (Sunday 00:00:00)'),
    sa.Column('payment_period_end', sa.DateTime(), nullable=False, comment='End of payment week (Saturday 23:59:59)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the charge'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about the charge'),
    sa.Column('reference_number', sa.String(length=100), nullable=True, comment='External reference number if applicable'),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'VOIDED', name='miscchargestatus'), nullable=False, comment='Current status of the charge'),
    sa.Column('posted_to_ledger', sa.Integer(), nullable=False, comment='Posted to ledger flag (0=no, 1=yes)'),
    sa.Column('ledger_posting_id', sa.String(length=64), nullable=True, comment='Reference to ledger posting (LP-YYYY-NNNNNN)'),
    sa.Column('ledger_balance_id', sa.String(length=64), nullable=True, comment='Reference to ledger balance (LB-YYYY-NNNNNN)'),
    sa.Column('posted_at', sa.DateTime(), nullable=True, comment='When posted to ledger'),
    sa.Column('posted_by', sa.Integer(), nullable=True, comment='User who posted to ledger'),
    sa.Column('voided_at', sa.DateTime(), nullable=True, comment='When charge was voided'),
    sa.Column('voided_by', sa.Integer(), nullable=True, comment='User who voided the charge'),
    sa.Column('voided_reason', sa.Text(), nullable=True, comment='Reason for voiding'),
    sa.Column('voided_ledger_posting_id', sa.String(length=64), nullable=True, comment='Reversal posting ID if voided'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', name='uq_misc_charge_expense_id')
    )
    op.create_index('idx_misc_charge_date', 'miscellaneous_charges', ['charge_date'], unique=False)
    op.create_index('idx_misc_charge_driver_lease', 'miscellaneous_charges', ['driver_id', 'lease_id'], unique=False)
    op.create_index('idx_misc_charge_period', 'miscellaneous_charges', ['payment_period_start', 'payment_period_end'], unique=False)
    op.create_index('idx_misc_charge_status_posted', 'miscellaneous_charges', ['status', 'posted_to_ledger'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_category'), 'miscellaneous_charges', ['category'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_charge_date'), 'miscellaneous_charges', ['charge_date'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_driver_id'), 'miscellaneous_charges', ['driver_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_expense_id'), 'miscellaneous_charges', ['expense_id'], unique=True)
    op.create_index(op.f('ix_miscellaneous_charges_lease_id'), 'miscellaneous_charges', ['lease_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_ledger_balance_id'), 'miscellaneous_charges', ['ledger_balance_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_ledger_posting_id'), 'miscellaneous_charges', ['ledger_posting_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_medallion_id'), 'miscellaneous_charges', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_payment_period_end'), 'miscellaneous_charges', ['payment_period_end'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_payment_period_start'), 'miscellaneous_charges', ['payment_period_start'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_posted_to_ledger'), 'miscellaneous_charges', ['posted_to_ledger'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_reference_number'), 'miscellaneous_charges', ['reference_number'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_status'), 'miscellaneous_charges', ['status'], unique=False)
    op.create_index(op.f('ix_miscellaneous_charges_vehicle_id'), 'miscellaneous_charges', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_miscellaneous_charges_vehicle_id'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_status'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_reference_number'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_posted_to_ledger'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_payment_period_start'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_payment_period_end'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_medallion_id'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_ledger_posting_id'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_ledger_balance_id'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_lease_id'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_expense_id'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_driver_id'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_charge_date'), table_name='miscellaneous_charges')
    op.drop_index(op.f('ix_miscellaneous_charges_category'), table_name='miscellaneous_charges')
    op.drop_index('idx_misc_charge_status_posted', table_name='miscellaneous_charges')
    op.drop_index('idx_misc_charge_period', table_name='miscellaneous_charges')
    op.drop_index('idx_misc_charge_driver_lease', table_name='miscellaneous_charges')
    op.drop_index('idx_misc_charge_date', table_name='miscellaneous_charges')
    op.drop_table('miscellaneous_charges')
    # ### end Alembic commands ###
