"""pvb models included

Revision ID: 24809dd71a94
Revises: 0c56dff2a32f
Create Date: 2025-11-03 08:59:08.138241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24809dd71a94'
down_revision: Union[str, Sequence[str], None] = '0c56dff2a32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvb_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original name of the uploaded CSV file.'),
    sa.Column('import_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the import process began.'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='pvbimportstatus'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False, comment='Total number of rows in the CSV file.'),
    sa.Column('successful_records', sa.Integer(), nullable=False, comment='Number of records successfully imported.'),
    sa.Column('failed_records', sa.Integer(), nullable=False, comment='Number of records that failed validation.'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvb_imports_id'), 'pvb_imports', ['id'], unique=False)
    op.create_index(op.f('ix_pvb_imports_status'), 'pvb_imports', ['status'], unique=False)
    op.create_table('pvb_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('CSV_IMPORT', 'MANUAL_ENTRY', name='pvbsource'), nullable=False),
    sa.Column('case_no', sa.String(length=255), nullable=True, comment='Links to the BPM case if created manually.'),
    sa.Column('plate', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('summons', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('issue_time', sa.Time(), nullable=True),
    sa.Column('fine', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('interest', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('IMPORTED', 'ASSOCIATION_PENDING', 'ASSOCIATION_FAILED', 'ASSOCIATED', 'POSTING_PENDING', 'POSTING_FAILED', 'POSTED_TO_LEDGER', name='pvbviolationstatus'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=True),
    sa.Column('lease_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['pvb_imports.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvb_violations_case_no'), 'pvb_violations', ['case_no'], unique=False)
    op.create_index(op.f('ix_pvb_violations_driver_id'), 'pvb_violations', ['driver_id'], unique=False)
    op.create_index(op.f('ix_pvb_violations_id'), 'pvb_violations', ['id'], unique=False)
    op.create_index(op.f('ix_pvb_violations_import_id'), 'pvb_violations', ['import_id'], unique=False)
    op.create_index(op.f('ix_pvb_violations_lease_id'), 'pvb_violations', ['lease_id'], unique=False)
    op.create_index(op.f('ix_pvb_violations_medallion_id'), 'pvb_violations', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_pvb_violations_plate'), 'pvb_violations', ['plate'], unique=False)
    op.create_index(op.f('ix_pvb_violations_source'), 'pvb_violations', ['source'], unique=False)
    op.create_index(op.f('ix_pvb_violations_status'), 'pvb_violations', ['status'], unique=False)
    op.create_index(op.f('ix_pvb_violations_summons'), 'pvb_violations', ['summons'], unique=True)
    op.create_index(op.f('ix_pvb_violations_vehicle_id'), 'pvb_violations', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pvb_violations_vehicle_id'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_summons'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_status'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_source'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_plate'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_medallion_id'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_lease_id'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_import_id'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_id'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_driver_id'), table_name='pvb_violations')
    op.drop_index(op.f('ix_pvb_violations_case_no'), table_name='pvb_violations')
    op.drop_table('pvb_violations')
    op.drop_index(op.f('ix_pvb_imports_status'), table_name='pvb_imports')
    op.drop_index(op.f('ix_pvb_imports_id'), table_name='pvb_imports')
    op.drop_table('pvb_imports')
    # ### end Alembic commands ###
