"""miscellaneous expenses models

Revision ID: 254e25f53ce8
Revises: a9c0ed2bc9cf
Create Date: 2025-11-04 00:18:46.584026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254e25f53ce8'
down_revision: Union[str, Sequence[str], None] = 'a9c0ed2bc9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miscellaneous_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.String(length=50), nullable=False, comment='System-generated unique ID (e.g., MISC-YYYY-#####).'),
    sa.Column('case_no', sa.String(length=255), nullable=False, comment='Links to the BPM case used for creation.'),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('medallion_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Dropdown category (e.g., Lost Key, Cleaning Fee).'),
    sa.Column('reference_number', sa.String(length=255), nullable=True, comment='Optional user-entered reference.'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='The total amount of the charge.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional free-text notes for details.'),
    sa.Column('status', sa.Enum('OPEN', 'RECOVERED', 'VOIDED', name='miscellaneousexpensestatus'), nullable=False),
    sa.Column('ledger_posting_ref', sa.String(length=255), nullable=False, comment='Reference to the LedgerPosting ID created upon save.'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miscellaneous_expenses_case_no'), 'miscellaneous_expenses', ['case_no'], unique=False)
    op.create_index(op.f('ix_miscellaneous_expenses_driver_id'), 'miscellaneous_expenses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_expenses_expense_id'), 'miscellaneous_expenses', ['expense_id'], unique=True)
    op.create_index(op.f('ix_miscellaneous_expenses_id'), 'miscellaneous_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_expenses_lease_id'), 'miscellaneous_expenses', ['lease_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_expenses_medallion_id'), 'miscellaneous_expenses', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_miscellaneous_expenses_status'), 'miscellaneous_expenses', ['status'], unique=False)
    op.create_index(op.f('ix_miscellaneous_expenses_vehicle_id'), 'miscellaneous_expenses', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_miscellaneous_expenses_vehicle_id'), table_name='miscellaneous_expenses')
    op.drop_index(op.f('ix_miscellaneous_expenses_status'), table_name='miscellaneous_expenses')
    op.drop_index(op.f('ix_miscellaneous_expenses_medallion_id'), table_name='miscellaneous_expenses')
    op.drop_index(op.f('ix_miscellaneous_expenses_lease_id'), table_name='miscellaneous_expenses')
    op.drop_index(op.f('ix_miscellaneous_expenses_id'), table_name='miscellaneous_expenses')
    op.drop_index(op.f('ix_miscellaneous_expenses_expense_id'), table_name='miscellaneous_expenses')
    op.drop_index(op.f('ix_miscellaneous_expenses_driver_id'), table_name='miscellaneous_expenses')
    op.drop_index(op.f('ix_miscellaneous_expenses_case_no'), table_name='miscellaneous_expenses')
    op.drop_table('miscellaneous_expenses')
    # ### end Alembic commands ###
