"""add reduced penalty amount column  added

Revision ID: 305c902156b7
Revises: 39905f203241
Create Date: 2025-12-04 14:49:46.188586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305c902156b7'
down_revision: Union[str, Sequence[str], None] = '39905f203241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tlc_violations', sa.Column('reduced_tlc_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tlc_violations', 'reduced_tlc_amount')
    # ### end Alembic commands ###
