"""ledger models included

Revision ID: 4958eee1a79d
Revises: 6cb65a8da121
Create Date: 2025-11-02 22:47:30.886046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4958eee1a79d'
down_revision: Union[str, Sequence[str], None] = '6cb65a8da121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('LEASE', 'REPAIR', 'LOAN', 'EZPASS', 'PVB', 'TLC', 'TAXES', 'MISC', 'EARNINGS', 'INTERIM_PAYMENT', 'DEPOSIT', 'CANCELLATION_FEE', name='postingcategory'), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False, comment='Traceability ID to the source obligation (e.g., RepairInvoice ID, Loan ID)'),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='The immutable initial obligation amount'),
    sa.Column('prior_balance', sa.Numeric(precision=10, scale=2), nullable=False, comment='Carried over unpaid portion from previous DTR cycle'),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False, comment='The current remaining unpaid portion of the obligation'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='balancestatus'), nullable=False),
    sa.Column('applied_payment_refs', sa.JSON(), nullable=True, comment='Stores a list of Posting_IDs for payments/earnings applied to this balance'),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=True),
    sa.Column('lease_id', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=64), nullable=True, comment='Denormalized for filtering/reconciliation'),
    sa.Column('plate', sa.String(length=255), nullable=True, comment='Denormalized for filtering/reconciliation'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_balances_category'), 'ledger_balances', ['category'], unique=False)
    op.create_index(op.f('ix_ledger_balances_driver_id'), 'ledger_balances', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ledger_balances_lease_id'), 'ledger_balances', ['lease_id'], unique=False)
    op.create_index(op.f('ix_ledger_balances_medallion_id'), 'ledger_balances', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_ledger_balances_reference_id'), 'ledger_balances', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_balances_vehicle_id'), 'ledger_balances', ['vehicle_id'], unique=False)
    op.create_table('ledger_postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('LEASE', 'REPAIR', 'LOAN', 'EZPASS', 'PVB', 'TLC', 'TAXES', 'MISC', 'EARNINGS', 'INTERIM_PAYMENT', 'DEPOSIT', 'CANCELLATION_FEE', name='postingcategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Positive for debit (obligation), Negative for credit (earning/payment)'),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='entrytype'), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'VOIDED', name='postingstatus'), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False, comment='Traceability ID to the source record (e.g., LeaseSchedule ID, RepairInvoice ID)'),
    sa.Column('reversal_for_id', sa.String(length=36), nullable=True, comment='If this is a reversal, points to the original posting ID'),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=True),
    sa.Column('lease_id', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=64), nullable=True, comment='Denormalized for filtering/reconciliation'),
    sa.Column('plate', sa.String(length=255), nullable=True, comment='Denormalized for filtering/reconciliation'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversal_for_id'], ['ledger_postings.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_postings_category'), 'ledger_postings', ['category'], unique=False)
    op.create_index(op.f('ix_ledger_postings_driver_id'), 'ledger_postings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ledger_postings_lease_id'), 'ledger_postings', ['lease_id'], unique=False)
    op.create_index(op.f('ix_ledger_postings_medallion_id'), 'ledger_postings', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_ledger_postings_reference_id'), 'ledger_postings', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_postings_vehicle_id'), 'ledger_postings', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_postings_vehicle_id'), table_name='ledger_postings')
    op.drop_index(op.f('ix_ledger_postings_reference_id'), table_name='ledger_postings')
    op.drop_index(op.f('ix_ledger_postings_medallion_id'), table_name='ledger_postings')
    op.drop_index(op.f('ix_ledger_postings_lease_id'), table_name='ledger_postings')
    op.drop_index(op.f('ix_ledger_postings_driver_id'), table_name='ledger_postings')
    op.drop_index(op.f('ix_ledger_postings_category'), table_name='ledger_postings')
    op.drop_table('ledger_postings')
    op.drop_index(op.f('ix_ledger_balances_vehicle_id'), table_name='ledger_balances')
    op.drop_index(op.f('ix_ledger_balances_reference_id'), table_name='ledger_balances')
    op.drop_index(op.f('ix_ledger_balances_medallion_id'), table_name='ledger_balances')
    op.drop_index(op.f('ix_ledger_balances_lease_id'), table_name='ledger_balances')
    op.drop_index(op.f('ix_ledger_balances_driver_id'), table_name='ledger_balances')
    op.drop_index(op.f('ix_ledger_balances_category'), table_name='ledger_balances')
    op.drop_table('ledger_balances')
    # ### end Alembic commands ###
