"""dtr models update

Revision ID: 4b30db73ccb3
Revises: 78efa37352ab
Create Date: 2025-11-20 12:24:10.085893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b30db73ccb3'
down_revision: Union[str, Sequence[str], None] = '78efa37352ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dtrs', sa.Column('subtotal_deductions', sa.Numeric(precision=10, scale=2), nullable=False, comment='Sum of all deductions'))
    op.add_column('dtrs', sa.Column('ach_batch_id', sa.Integer(), nullable=True))
    op.add_column('dtrs', sa.Column('additional_drivers_detail', sa.JSON(), nullable=True, comment='Array of additional driver detail sections. Each entry contains:\n        {\n            "driver_id": int,\n            "driver_name": str,\n            "tlc_license": str,\n            "cc_earnings": decimal,\n            "taxes_charges": {...},\n            "ezpass_tolls": [...],\n            "pvb_violations": [...],\n            "trip_log": [...],\n            "alerts": {...}\n        }\n        '))
    op.alter_column('dtrs', 'lease_id',
               existing_type=mysql.INTEGER(),
               comment='Foreign key to lease (ONE DTR PER LEASE)',
               existing_nullable=False)
    op.alter_column('dtrs', 'driver_id',
               existing_type=mysql.INTEGER(),
               comment='Primary driver (leaseholder) - for reference only',
               existing_nullable=False)
    op.alter_column('dtrs', 'gross_cc_earnings',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Total credit card earnings from CURB (ALL drivers consolidated)',
               existing_comment='Total credit card earnings from CURB',
               existing_nullable=False)
    op.alter_column('dtrs', 'total_gross_earnings',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Total gross earnings (CC + Cash)',
               existing_comment='Total gross earnings',
               existing_nullable=False)
    op.alter_column('dtrs', 'lease_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Weekly lease charge (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'mta_tif_fees',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='MTA, TIF, Congestion, CBDT, Airport fees (ALL drivers)',
               existing_comment='MTA, TIF, Congestion, CRBT, Airport fees',
               existing_nullable=False)
    op.alter_column('dtrs', 'ezpass_tolls',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='EZPass tolls (ALL drivers, outstanding as of period end)',
               existing_nullable=False)
    op.alter_column('dtrs', 'violation_tickets',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='PVB violations (ALL drivers, outstanding as of period end)',
               existing_comment='PVB violations',
               existing_nullable=False)
    op.alter_column('dtrs', 'tlc_tickets',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='TLC tickets (lease/medallion level only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'repairs',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Repair charges for this period (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'driver_loans',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Loan installments due (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'misc_charges',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Miscellaneous charges (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'prior_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Balance carried forward from previous period',
               existing_comment='Outstanding balance from previous periods',
               existing_nullable=False)
    op.alter_column('dtrs', 'net_earnings',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Gross earnings - subtotal deductions - prior balance',
               existing_comment='Gross earnings - subtotal - prior balance',
               existing_nullable=False)
    op.alter_column('dtrs', 'total_due_to_driver',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Final amount due to driver (max of 0 and net_earnings)',
               existing_comment='Final amount payable to driver (can be negative)',
               existing_nullable=False)
    op.alter_column('dtrs', 'payment_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Date payment was processed',
               existing_nullable=True)
    op.alter_column('dtrs', 'ach_batch_number',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment=None,
               existing_comment='ACH batch number if paid via ACH',
               existing_nullable=True)
    op.alter_column('dtrs', 'check_number',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Check number if paid by check',
               existing_nullable=True)
    op.alter_column('dtrs', 'tax_breakdown',
               existing_type=mysql.JSON(),
               comment='Detailed tax breakdown (Airport, CBDT, Congestion, MTA, TIF) - consolidated all drivers',
               existing_comment='Detailed tax breakdown (Airport, CBDT, Congestion, MTA, TIF)',
               existing_nullable=True)
    op.alter_column('dtrs', 'ezpass_detail',
               existing_type=mysql.JSON(),
               comment='EZPass transaction details - consolidated all drivers',
               existing_comment='EZPass transaction details',
               existing_nullable=True)
    op.alter_column('dtrs', 'pvb_detail',
               existing_type=mysql.JSON(),
               comment='PVB violation details - consolidated all drivers',
               existing_comment='PVB violation details',
               existing_nullable=True)
    op.alter_column('dtrs', 'tlc_detail',
               existing_type=mysql.JSON(),
               comment='TLC ticket details - lease level only',
               existing_comment='TLC ticket details',
               existing_nullable=True)
    op.alter_column('dtrs', 'repair_detail',
               existing_type=mysql.JSON(),
               comment='Repair invoice details - primary driver only',
               existing_comment='Repair invoice details',
               existing_nullable=True)
    op.alter_column('dtrs', 'loan_detail',
               existing_type=mysql.JSON(),
               comment='Loan installment details - primary driver only',
               existing_comment='Loan installment details',
               existing_nullable=True)
    op.alter_column('dtrs', 'trip_log',
               existing_type=mysql.JSON(),
               comment='Credit card trip log from CURB - ALL drivers with TLC license identification',
               existing_comment='Credit card trip log from CURB',
               existing_nullable=True)
    op.alter_column('dtrs', 'alerts',
               existing_type=mysql.JSON(),
               comment='Vehicle and driver alerts (expiry dates, etc.) - includes all drivers',
               existing_comment='Vehicle and driver alerts (expiry dates, etc.)',
               existing_nullable=True)
    op.create_index(op.f('ix_dtrs_ach_batch_id'), 'dtrs', ['ach_batch_id'], unique=False)
    op.create_unique_constraint('uq_dtr_lease_period', 'dtrs', ['lease_id', 'period_start_date'])
    op.drop_constraint(op.f('dtrs_ibfk_6'), 'dtrs', type_='foreignkey')
    op.create_foreign_key(None, 'dtrs', 'ach_batches', ['ach_batch_id'], ['id'])
    op.create_table_comment(
        'dtrs',
        'Driver Transaction Receipts - ONE DTR PER LEASE PER PERIOD',
        existing_comment=None,
        schema=None
    )
    op.drop_column('dtrs', 'is_additional_driver_dtr')
    op.drop_column('dtrs', 'parent_dtr_id')
    op.drop_column('dtrs', 'subtotal_charges')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dtrs', sa.Column('subtotal_charges', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='Sum of all charges'))
    op.add_column('dtrs', sa.Column('parent_dtr_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Reference to primary DTR if this is additional driver'))
    op.add_column('dtrs', sa.Column('is_additional_driver_dtr', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='True if this is an additional driver DTR'))
    op.drop_table_comment(
        'dtrs',
        existing_comment='Driver Transaction Receipts - ONE DTR PER LEASE PER PERIOD',
        schema=None
    )
    op.drop_constraint(None, 'dtrs', type_='foreignkey')
    op.create_foreign_key(op.f('dtrs_ibfk_6'), 'dtrs', 'dtrs', ['parent_dtr_id'], ['id'])
    op.drop_constraint('uq_dtr_lease_period', 'dtrs', type_='unique')
    op.drop_index(op.f('ix_dtrs_ach_batch_id'), table_name='dtrs')
    op.alter_column('dtrs', 'alerts',
               existing_type=mysql.JSON(),
               comment='Vehicle and driver alerts (expiry dates, etc.)',
               existing_comment='Vehicle and driver alerts (expiry dates, etc.) - includes all drivers',
               existing_nullable=True)
    op.alter_column('dtrs', 'trip_log',
               existing_type=mysql.JSON(),
               comment='Credit card trip log from CURB',
               existing_comment='Credit card trip log from CURB - ALL drivers with TLC license identification',
               existing_nullable=True)
    op.alter_column('dtrs', 'loan_detail',
               existing_type=mysql.JSON(),
               comment='Loan installment details',
               existing_comment='Loan installment details - primary driver only',
               existing_nullable=True)
    op.alter_column('dtrs', 'repair_detail',
               existing_type=mysql.JSON(),
               comment='Repair invoice details',
               existing_comment='Repair invoice details - primary driver only',
               existing_nullable=True)
    op.alter_column('dtrs', 'tlc_detail',
               existing_type=mysql.JSON(),
               comment='TLC ticket details',
               existing_comment='TLC ticket details - lease level only',
               existing_nullable=True)
    op.alter_column('dtrs', 'pvb_detail',
               existing_type=mysql.JSON(),
               comment='PVB violation details',
               existing_comment='PVB violation details - consolidated all drivers',
               existing_nullable=True)
    op.alter_column('dtrs', 'ezpass_detail',
               existing_type=mysql.JSON(),
               comment='EZPass transaction details',
               existing_comment='EZPass transaction details - consolidated all drivers',
               existing_nullable=True)
    op.alter_column('dtrs', 'tax_breakdown',
               existing_type=mysql.JSON(),
               comment='Detailed tax breakdown (Airport, CBDT, Congestion, MTA, TIF)',
               existing_comment='Detailed tax breakdown (Airport, CBDT, Congestion, MTA, TIF) - consolidated all drivers',
               existing_nullable=True)
    op.alter_column('dtrs', 'check_number',
               existing_type=mysql.VARCHAR(length=50),
               comment='Check number if paid by check',
               existing_nullable=True)
    op.alter_column('dtrs', 'ach_batch_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               comment='ACH batch number if paid via ACH',
               existing_nullable=True)
    op.alter_column('dtrs', 'payment_date',
               existing_type=mysql.DATETIME(),
               comment='Date payment was processed',
               existing_nullable=True)
    op.alter_column('dtrs', 'total_due_to_driver',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Final amount payable to driver (can be negative)',
               existing_comment='Final amount due to driver (max of 0 and net_earnings)',
               existing_nullable=False)
    op.alter_column('dtrs', 'net_earnings',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Gross earnings - subtotal - prior balance',
               existing_comment='Gross earnings - subtotal deductions - prior balance',
               existing_nullable=False)
    op.alter_column('dtrs', 'prior_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Outstanding balance from previous periods',
               existing_comment='Balance carried forward from previous period',
               existing_nullable=False)
    op.alter_column('dtrs', 'misc_charges',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Miscellaneous charges (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'driver_loans',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Loan installments due (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'repairs',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Repair charges for this period (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'tlc_tickets',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='TLC tickets (lease/medallion level only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'violation_tickets',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='PVB violations',
               existing_comment='PVB violations (ALL drivers, outstanding as of period end)',
               existing_nullable=False)
    op.alter_column('dtrs', 'ezpass_tolls',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='EZPass tolls (ALL drivers, outstanding as of period end)',
               existing_nullable=False)
    op.alter_column('dtrs', 'mta_tif_fees',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='MTA, TIF, Congestion, CRBT, Airport fees',
               existing_comment='MTA, TIF, Congestion, CBDT, Airport fees (ALL drivers)',
               existing_nullable=False)
    op.alter_column('dtrs', 'lease_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Weekly lease charge (primary driver only)',
               existing_nullable=False)
    op.alter_column('dtrs', 'total_gross_earnings',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Total gross earnings',
               existing_comment='Total gross earnings (CC + Cash)',
               existing_nullable=False)
    op.alter_column('dtrs', 'gross_cc_earnings',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Total credit card earnings from CURB',
               existing_comment='Total credit card earnings from CURB (ALL drivers consolidated)',
               existing_nullable=False)
    op.alter_column('dtrs', 'driver_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Primary driver (leaseholder) - for reference only',
               existing_nullable=False)
    op.alter_column('dtrs', 'lease_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Foreign key to lease (ONE DTR PER LEASE)',
               existing_nullable=False)
    op.drop_column('dtrs', 'additional_drivers_detail')
    op.drop_column('dtrs', 'ach_batch_id')
    op.drop_column('dtrs', 'subtotal_deductions')
    # ### end Alembic commands ###
