"""loan models

Revision ID: 54b789daad66
Revises: c0ba5929016b
Create Date: 2025-11-03 11:56:31.313095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b789daad66'
down_revision: Union[str, Sequence[str], None] = 'c0ba5929016b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=50), nullable=False, comment='System-generated unique ID for the loan (e.g., DLN-YYYY-###).'),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('medallion_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='The total principal amount of the loan.'),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Annual interest rate (e.g., 10.00 for 10%).'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'HOLD', 'CANCELLED', name='loanstatus'), nullable=False),
    sa.Column('start_week', sa.Date(), nullable=False, comment='The Sunday that marks the beginning of the first repayment period.'),
    sa.Column('loan_date', sa.Date(), nullable=False, comment='The date the loan was disbursed.'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_loans_driver_id'), 'driver_loans', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_loans_id'), 'driver_loans', ['id'], unique=False)
    op.create_index(op.f('ix_driver_loans_lease_id'), 'driver_loans', ['lease_id'], unique=False)
    op.create_index(op.f('ix_driver_loans_loan_id'), 'driver_loans', ['loan_id'], unique=True)
    op.create_index(op.f('ix_driver_loans_medallion_id'), 'driver_loans', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_driver_loans_status'), 'driver_loans', ['status'], unique=False)
    op.create_table('loan_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.String(length=60), nullable=False, comment='Unique ID for the installment (e.g., DLN-YYYY-###-01).'),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='The principal portion of this installment.'),
    sa.Column('interest_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='The calculated interest portion for this period.'),
    sa.Column('total_due', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount due for this installment (Principal + Interest).'),
    sa.Column('status', sa.Enum('SCHEDULED', 'DUE', 'POSTED', 'PAID', name='loaninstallmentstatus'), nullable=False),
    sa.Column('ledger_posting_ref', sa.String(length=255), nullable=True, comment='Reference to the LedgerPosting ID.'),
    sa.Column('posted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['driver_loans.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_installments_id'), 'loan_installments', ['id'], unique=False)
    op.create_index(op.f('ix_loan_installments_installment_id'), 'loan_installments', ['installment_id'], unique=True)
    op.create_index(op.f('ix_loan_installments_loan_id'), 'loan_installments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_installments_status'), 'loan_installments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_installments_status'), table_name='loan_installments')
    op.drop_index(op.f('ix_loan_installments_loan_id'), table_name='loan_installments')
    op.drop_index(op.f('ix_loan_installments_installment_id'), table_name='loan_installments')
    op.drop_index(op.f('ix_loan_installments_id'), table_name='loan_installments')
    op.drop_table('loan_installments')
    op.drop_index(op.f('ix_driver_loans_status'), table_name='driver_loans')
    op.drop_index(op.f('ix_driver_loans_medallion_id'), table_name='driver_loans')
    op.drop_index(op.f('ix_driver_loans_loan_id'), table_name='driver_loans')
    op.drop_index(op.f('ix_driver_loans_lease_id'), table_name='driver_loans')
    op.drop_index(op.f('ix_driver_loans_id'), table_name='driver_loans')
    op.drop_index(op.f('ix_driver_loans_driver_id'), table_name='driver_loans')
    op.drop_table('driver_loans')
    # ### end Alembic commands ###
