"""make_curb_cab_number_nullable

Revision ID: 674416c16ccb
Revises: 0287018013c8
Create Date: 2025-11-06 13:04:04.332038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '674416c16ccb'
down_revision: Union[str, Sequence[str], None] = '0287018013c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curb_trips', 'curb_cab_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='The raw cab/medallion number from CURB.')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curb_trips', 'curb_cab_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='The raw cab/medallion number from CURB.')
    # ### end Alembic commands ###
