"""lease termination column added

Revision ID: 6b2dbe8bd4c7
Revises: 1ff97e38f26f
Create Date: 2025-11-12 12:56:38.649685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2dbe8bd4c7'
down_revision: Union[str, Sequence[str], None] = '7cd387b98b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('termination_date', sa.Date(), nullable=True, comment='Date when the lease was terminated'))
    op.add_column('leases', sa.Column('termination_reason', sa.String(length=500), nullable=True, comment='Reason for lease termination'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leases', 'termination_reason')
    op.drop_column('leases', 'termination_date')
    # ### end Alembic commands ###
