"""ezpass_class Column added in Ezpass Table

Revision ID: 78efa37352ab
Revises: 55331e789407
Create Date: 2025-11-19 11:07:19.632936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78efa37352ab'
down_revision: Union[str, Sequence[str], None] = '55331e789407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ezpass_transactions', sa.Column('ezpass_class', sa.String(length=50), nullable=True, comment="The 'CLASS' column from the CSV, stored for reference."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ezpass_transactions', 'ezpass_class')
    # ### end Alembic commands ###
