"""add additional columns in pvb

Revision ID: 79543a590be9
Revises: 567c7608b22a
Create Date: 2025-12-02 09:35:25.117478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79543a590be9'
down_revision: Union[str, Sequence[str], None] = '567c7608b22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pvb_violations', sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pvb_violations', sa.Column('driver_payment_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pvb_violations', sa.Column('is_terminated', sa.Boolean(), nullable=False))
    op.add_column('pvb_violations', sa.Column('non_program', sa.Boolean(), nullable=True))
    op.add_column('pvb_violations', sa.Column('system_entry_date', sa.Date(), nullable=True))
    op.add_column('pvb_violations', sa.Column('new_issue', sa.Boolean(), nullable=False))
    op.add_column('pvb_violations', sa.Column('hearing_ind', sa.String(length=50), nullable=True))
    op.add_column('pvb_violations', sa.Column('penalty_warning', sa.String(length=50), nullable=True))
    op.add_column('pvb_violations', sa.Column('judgement', sa.Boolean(), nullable=True))
    op.add_column('pvb_violations', sa.Column('payment', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pvb_violations', sa.Column('ng_pmt', sa.Boolean(), nullable=True))
    op.add_column('pvb_violations', sa.Column('front_or_opp', sa.String(length=150), nullable=True))
    op.add_column('pvb_violations', sa.Column('house_number', sa.String(length=50), nullable=True))
    op.add_column('pvb_violations', sa.Column('intersect_street', sa.String(length=255), nullable=True))
    op.add_column('pvb_violations', sa.Column('geo_location', sa.String(length=255), nullable=True))
    op.add_column('pvb_violations', sa.Column('street_code_1', sa.String(length=50), nullable=True))
    op.add_column('pvb_violations', sa.Column('street_code_2', sa.String(length=50), nullable=True))
    op.add_column('pvb_violations', sa.Column('street_code_3', sa.String(length=50), nullable=True))
    op.add_column('pvb_violations', sa.Column('violation_code', sa.String(length=255), nullable=True))
    op.add_column('pvb_violations', sa.Column('violation_country', sa.String(length=255), nullable=True))
    op.add_column('pvb_violations', sa.Column('street_name', sa.String(length=255), nullable=True))
    op.add_column('tlc_violations', sa.Column('driver_payable', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tlc_violations', 'driver_payable')
    op.drop_column('pvb_violations', 'street_name')
    op.drop_column('pvb_violations', 'violation_country')
    op.drop_column('pvb_violations', 'violation_code')
    op.drop_column('pvb_violations', 'street_code_3')
    op.drop_column('pvb_violations', 'street_code_2')
    op.drop_column('pvb_violations', 'street_code_1')
    op.drop_column('pvb_violations', 'geo_location')
    op.drop_column('pvb_violations', 'intersect_street')
    op.drop_column('pvb_violations', 'house_number')
    op.drop_column('pvb_violations', 'front_or_opp')
    op.drop_column('pvb_violations', 'ng_pmt')
    op.drop_column('pvb_violations', 'payment')
    op.drop_column('pvb_violations', 'judgement')
    op.drop_column('pvb_violations', 'penalty_warning')
    op.drop_column('pvb_violations', 'hearing_ind')
    op.drop_column('pvb_violations', 'new_issue')
    op.drop_column('pvb_violations', 'system_entry_date')
    op.drop_column('pvb_violations', 'non_program')
    op.drop_column('pvb_violations', 'is_terminated')
    op.drop_column('pvb_violations', 'driver_payment_amount')
    op.drop_column('pvb_violations', 'processing_fee')
    # ### end Alembic commands ###
