"""tlc violation models

Revision ID: 980a0a609b0d
Revises: 54b789daad66
Create Date: 2025-11-03 12:24:13.692259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980a0a609b0d'
down_revision: Union[str, Sequence[str], None] = '54b789daad66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tlc_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.String(length=255), nullable=False, comment='Links to the BPM case used for creation.'),
    sa.Column('summons_no', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('issue_time', sa.Time(), nullable=True),
    sa.Column('violation_type', sa.Enum('FI', 'FN', 'RF', name='tlcviolationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='Required only if type is FN.'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Base ticket amount.'),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=10, scale=2), nullable=False, comment='Calculated as Amount + Service Fee.'),
    sa.Column('disposition', sa.Enum('PAID', 'REDUCED', 'DISMISSED', name='tlcdisposition'), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('attachment_document_id', sa.Integer(), nullable=False, comment='FK to the uploaded ticket scan.'),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'REVERSED', name='tlcviolationstatus'), nullable=False),
    sa.Column('original_posting_id', sa.String(length=255), nullable=True, comment='Reference to the initial ledger posting.'),
    sa.Column('reversal_posting_id', sa.String(length=255), nullable=True, comment='Reference to the reversal posting if disposition is changed.'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['attachment_document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tlc_violations_case_no'), 'tlc_violations', ['case_no'], unique=False)
    op.create_index(op.f('ix_tlc_violations_driver_id'), 'tlc_violations', ['driver_id'], unique=False)
    op.create_index(op.f('ix_tlc_violations_id'), 'tlc_violations', ['id'], unique=False)
    op.create_index(op.f('ix_tlc_violations_lease_id'), 'tlc_violations', ['lease_id'], unique=False)
    op.create_index(op.f('ix_tlc_violations_medallion_id'), 'tlc_violations', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_tlc_violations_summons_no'), 'tlc_violations', ['summons_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tlc_violations_summons_no'), table_name='tlc_violations')
    op.drop_index(op.f('ix_tlc_violations_medallion_id'), table_name='tlc_violations')
    op.drop_index(op.f('ix_tlc_violations_lease_id'), table_name='tlc_violations')
    op.drop_index(op.f('ix_tlc_violations_id'), table_name='tlc_violations')
    op.drop_index(op.f('ix_tlc_violations_driver_id'), table_name='tlc_violations')
    op.drop_index(op.f('ix_tlc_violations_case_no'), table_name='tlc_violations')
    op.drop_table('tlc_violations')
    # ### end Alembic commands ###
