"""interim payments models

Revision ID: a9c0ed2bc9cf
Revises: 980a0a609b0d
Create Date: 2025-11-03 23:54:57.373044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c0ed2bc9cf'
down_revision: Union[str, Sequence[str], None] = '980a0a609b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interim_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False, comment='System-generated unique ID for the payment (e.g., INTPAY-[YYYY]-[#####]).'),
    sa.Column('case_no', sa.String(length=255), nullable=False, comment='Links to the BPM case used for creation.'),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='The total amount received from the driver.'),
    sa.Column('payment_method', sa.Enum('CASH', 'CHECK', 'ACH', name='paymentmethod'), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True, comment='Optional notes from the cashier.'),
    sa.Column('allocations', sa.JSON(), nullable=True, comment='A JSON object detailing how the payment was allocated to different ledger balances.'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interim_payments_case_no'), 'interim_payments', ['case_no'], unique=False)
    op.create_index(op.f('ix_interim_payments_driver_id'), 'interim_payments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_interim_payments_id'), 'interim_payments', ['id'], unique=False)
    op.create_index(op.f('ix_interim_payments_lease_id'), 'interim_payments', ['lease_id'], unique=False)
    op.create_index(op.f('ix_interim_payments_payment_id'), 'interim_payments', ['payment_id'], unique=True)
    op.add_column('tlc_violations', sa.Column('plate', sa.String(length=50), nullable=False, comment='License plate number of the vehicle.'))
    op.add_column('tlc_violations', sa.Column('state', sa.String(length=10), nullable=False, comment='State of the license plate.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tlc_violations', 'state')
    op.drop_column('tlc_violations', 'plate')
    op.drop_index(op.f('ix_interim_payments_payment_id'), table_name='interim_payments')
    op.drop_index(op.f('ix_interim_payments_lease_id'), table_name='interim_payments')
    op.drop_index(op.f('ix_interim_payments_id'), table_name='interim_payments')
    op.drop_index(op.f('ix_interim_payments_driver_id'), table_name='interim_payments')
    op.drop_index(op.f('ix_interim_payments_case_no'), table_name='interim_payments')
    op.drop_table('interim_payments')
    # ### end Alembic commands ###
