"""Included receipt fields

Revision ID: aaed9d2917f3
Revises: 305c902156b7
Create Date: 2025-12-11 06:54:15.312306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaed9d2917f3'
down_revision: Union[str, Sequence[str], None] = '305c902156b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_loans', sa.Column('receipt_s3_key', sa.String(length=512), nullable=True, comment='S3 key where the loan receipt PDF is stored'))
    op.add_column('driver_loans', sa.Column('receipt_url', sa.String(length=1024), nullable=True, comment='Presigned URL for accessing the loan receipt'))
    op.add_column('interim_payments', sa.Column('receipt_s3_key', sa.String(length=500), nullable=True, comment='S3 key/path for the generated receipt PDF'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interim_payments', 'receipt_s3_key')
    op.drop_column('driver_loans', 'receipt_url')
    op.drop_column('driver_loans', 'receipt_s3_key')
    # ### end Alembic commands ###
