"""add few columns in tlc_violation table

Revision ID: be613086a6a7
Revises: b4ed624bcff2
Create Date: 2025-11-26 12:28:34.269760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be613086a6a7'
down_revision: Union[str, Sequence[str], None] = 'b4ed624bcff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tlc_violations', sa.Column('due_date', sa.Date(), nullable=False))
    op.add_column('tlc_violations', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('tlc_violations', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.alter_column('tlc_violations', 'medallion_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tlc_violations', 'lease_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tlc_violations', 'attachment_document_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='FK to the uploaded ticket scan.')
    op.create_index(op.f('ix_tlc_violations_vehicle_id'), 'tlc_violations', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'tlc_violations', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tlc_violations', type_='foreignkey')
    op.drop_index(op.f('ix_tlc_violations_vehicle_id'), table_name='tlc_violations')
    op.alter_column('tlc_violations', 'attachment_document_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='FK to the uploaded ticket scan.')
    op.alter_column('tlc_violations', 'lease_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tlc_violations', 'medallion_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('tlc_violations', 'vehicle_id')
    op.drop_column('tlc_violations', 'note')
    op.drop_column('tlc_violations', 'due_date')
    # ### end Alembic commands ###
