"""included lease schedule fields

Revision ID: cbe5de5b8cb2
Revises: 3267b820a5f4
Create Date: 2025-10-30 06:55:33.435665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe5de5b8cb2'
down_revision: Union[str, Sequence[str], None] = '3267b820a5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lease_schedule', sa.Column('posted_to_ledger', sa.Integer(), nullable=True, comment='0 = not posted, 1 = posted to ledger'))
    op.add_column('lease_schedule', sa.Column('posted_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when posted to ledger'))
    op.add_column('lease_schedule', sa.Column('ledger_posting_id', sa.String(length=50), nullable=True, comment='Reference to ledger posting'))
    op.add_column('lease_schedule', sa.Column('ledger_balance_id', sa.String(length=50), nullable=True, comment='Reference to ledger balance'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lease_schedule', 'ledger_balance_id')
    op.drop_column('lease_schedule', 'ledger_posting_id')
    op.drop_column('lease_schedule', 'posted_on')
    op.drop_column('lease_schedule', 'posted_to_ledger')
    # ### end Alembic commands ###
