"""curb models

Revision ID: ccec8c3843f5
Revises: 4958eee1a79d
Create Date: 2025-11-03 07:37:39.344714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccec8c3843f5'
down_revision: Union[str, Sequence[str], None] = '4958eee1a79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curb_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curb_trip_id', sa.String(length=255), nullable=False, comment='Unique identifier for the trip from CURB (e.g., ROWID).'),
    sa.Column('curb_period', sa.String(length=50), nullable=True, comment="The accounting period from CURB (e.g., '201903')."),
    sa.Column('status', sa.Enum('UNRECONCILED', 'RECONCILED', 'POSTED_TO_LEDGER', 'ERROR', name='curbtripstatus'), nullable=False, comment='The processing status of the trip within the BAT system.'),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lease_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=True),
    sa.Column('curb_driver_id', sa.String(length=100), nullable=False, comment='The raw driver identifier from CURB.'),
    sa.Column('curb_cab_number', sa.String(length=100), nullable=False, comment='The raw cab/medallion number from CURB.'),
    sa.Column('plate', sa.String(length=50), nullable=True, comment='Vehicle plate number, if available.'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='The start date and time of the trip.'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='The end date and time of the trip.'),
    sa.Column('fare', sa.Numeric(precision=10, scale=2), nullable=False, comment='Base fare amount.'),
    sa.Column('tips', sa.Numeric(precision=10, scale=2), nullable=False, comment='Tip amount.'),
    sa.Column('tolls', sa.Numeric(precision=10, scale=2), nullable=False, comment='Toll charges.'),
    sa.Column('extras', sa.Numeric(precision=10, scale=2), nullable=True, comment='Extra charges.'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount charged for the trip.'),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=True, comment='State Surcharge (TAX).'),
    sa.Column('improvement_surcharge', sa.Numeric(precision=10, scale=2), nullable=True, comment='Improvement Surcharge (IMPTAX / TIF).'),
    sa.Column('congestion_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='Congestion Fee (CongFee).'),
    sa.Column('airport_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='Airport Fee (airportFee).'),
    sa.Column('cbdt_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='Congestion Relief Zone Toll (cbdt).'),
    sa.Column('payment_type', sa.Enum('CASH', 'CREDIT_CARD', 'PRIVATE', 'UNKNOWN', name='paymenttype'), nullable=False, comment='Method of payment (Cash, Credit, etc.).'),
    sa.Column('reconciliation_id', sa.String(length=100), nullable=True, comment='The reconciliation identifier sent back to CURB.'),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the trip was reconciled.'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curb_trips_curb_cab_number'), 'curb_trips', ['curb_cab_number'], unique=False)
    op.create_index(op.f('ix_curb_trips_curb_driver_id'), 'curb_trips', ['curb_driver_id'], unique=False)
    op.create_index(op.f('ix_curb_trips_curb_trip_id'), 'curb_trips', ['curb_trip_id'], unique=True)
    op.create_index(op.f('ix_curb_trips_driver_id'), 'curb_trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_curb_trips_id'), 'curb_trips', ['id'], unique=False)
    op.create_index(op.f('ix_curb_trips_lease_id'), 'curb_trips', ['lease_id'], unique=False)
    op.create_index(op.f('ix_curb_trips_medallion_id'), 'curb_trips', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_curb_trips_reconciliation_id'), 'curb_trips', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_curb_trips_status'), 'curb_trips', ['status'], unique=False)
    op.create_index(op.f('ix_curb_trips_vehicle_id'), 'curb_trips', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curb_trips_vehicle_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_status'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_reconciliation_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_medallion_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_lease_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_driver_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_curb_trip_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_curb_driver_id'), table_name='curb_trips')
    op.drop_index(op.f('ix_curb_trips_curb_cab_number'), table_name='curb_trips')
    op.drop_table('curb_trips')
    # ### end Alembic commands ###
