"""dtr models included

Revision ID: d002f43e6850
Revises: 254e25f53ce8
Create Date: 2025-11-06 05:37:00.062741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd002f43e6850'
down_revision: Union[str, Sequence[str], None] = '254e25f53ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtr_number', sa.String(length=50), nullable=False, comment='Unique DTR number (BAT system generated)'),
    sa.Column('receipt_number', sa.String(length=50), nullable=False, comment='Receipt number for payment tracking'),
    sa.Column('period_start_date', sa.Date(), nullable=False, comment='Payment period start (Sunday 00:00)'),
    sa.Column('period_end_date', sa.Date(), nullable=False, comment='Payment period end (Saturday 23:59)'),
    sa.Column('generation_date', sa.DateTime(), nullable=False, comment='Date and time DTR was generated'),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('medallion_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'FINALIZED', 'PAID', 'VOIDED', name='dtrstatus'), nullable=False),
    sa.Column('gross_cc_earnings', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total credit card earnings from CURB'),
    sa.Column('gross_cash_earnings', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total cash earnings (if tracked)'),
    sa.Column('total_gross_earnings', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total gross earnings'),
    sa.Column('lease_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mta_tif_fees', sa.Numeric(precision=10, scale=2), nullable=False, comment='MTA, TIF, Congestion, CRBT, Airport fees'),
    sa.Column('ezpass_tolls', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('violation_tickets', sa.Numeric(precision=10, scale=2), nullable=False, comment='PVB violations'),
    sa.Column('tlc_tickets', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('repairs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_loans', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('misc_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_charges', sa.Numeric(precision=10, scale=2), nullable=False, comment='Sum of all charges'),
    sa.Column('prior_balance', sa.Numeric(precision=10, scale=2), nullable=False, comment='Outstanding balance from previous periods'),
    sa.Column('net_earnings', sa.Numeric(precision=10, scale=2), nullable=False, comment='Gross earnings - subtotal - prior balance'),
    sa.Column('total_due_to_driver', sa.Numeric(precision=10, scale=2), nullable=False, comment='Final amount payable to driver (can be negative)'),
    sa.Column('payment_method', sa.Enum('ACH', 'CHECK', 'CASH', 'DIRECT_DEPOSIT', name='paymentmethod'), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True, comment='Date payment was processed'),
    sa.Column('ach_batch_number', sa.String(length=50), nullable=True, comment='ACH batch number if paid via ACH'),
    sa.Column('check_number', sa.String(length=50), nullable=True, comment='Check number if paid by check'),
    sa.Column('account_number_masked', sa.String(length=20), nullable=True, comment='Last 4 digits of bank account (for security)'),
    sa.Column('is_additional_driver_dtr', sa.Boolean(), nullable=False, comment='True if this is an additional driver DTR'),
    sa.Column('parent_dtr_id', sa.Integer(), nullable=True, comment='Reference to primary DTR if this is additional driver'),
    sa.Column('tax_breakdown', sa.JSON(), nullable=True, comment='Detailed tax breakdown (Airport, CBDT, Congestion, MTA, TIF)'),
    sa.Column('ezpass_detail', sa.JSON(), nullable=True, comment='EZPass transaction details'),
    sa.Column('pvb_detail', sa.JSON(), nullable=True, comment='PVB violation details'),
    sa.Column('tlc_detail', sa.JSON(), nullable=True, comment='TLC ticket details'),
    sa.Column('repair_detail', sa.JSON(), nullable=True, comment='Repair invoice details'),
    sa.Column('loan_detail', sa.JSON(), nullable=True, comment='Loan installment details'),
    sa.Column('trip_log', sa.JSON(), nullable=True, comment='Credit card trip log from CURB'),
    sa.Column('alerts', sa.JSON(), nullable=True, comment='Vehicle and driver alerts (expiry dates, etc.)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or comments'),
    sa.Column('voided_reason', sa.Text(), nullable=True, comment='Reason if DTR was voided'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.ForeignKeyConstraint(['medallion_id'], ['medallions.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_dtr_id'], ['dtrs.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dtrs_ach_batch_number'), 'dtrs', ['ach_batch_number'], unique=False)
    op.create_index(op.f('ix_dtrs_driver_id'), 'dtrs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_dtrs_dtr_number'), 'dtrs', ['dtr_number'], unique=True)
    op.create_index(op.f('ix_dtrs_id'), 'dtrs', ['id'], unique=False)
    op.create_index(op.f('ix_dtrs_lease_id'), 'dtrs', ['lease_id'], unique=False)
    op.create_index(op.f('ix_dtrs_medallion_id'), 'dtrs', ['medallion_id'], unique=False)
    op.create_index(op.f('ix_dtrs_period_end_date'), 'dtrs', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_dtrs_period_start_date'), 'dtrs', ['period_start_date'], unique=False)
    op.create_index(op.f('ix_dtrs_receipt_number'), 'dtrs', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_dtrs_status'), 'dtrs', ['status'], unique=False)
    op.create_index(op.f('ix_dtrs_vehicle_id'), 'dtrs', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dtrs_vehicle_id'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_status'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_receipt_number'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_period_start_date'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_period_end_date'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_medallion_id'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_lease_id'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_id'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_dtr_number'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_driver_id'), table_name='dtrs')
    op.drop_index(op.f('ix_dtrs_ach_batch_number'), table_name='dtrs')
    op.drop_table('dtrs')
    # ### end Alembic commands ###
