"""update tlc in drivers

Revision ID: f4a763f0aef0
Revises: 5027ff760272
Create Date: 2025-11-17 13:14:22.201422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a763f0aef0'
down_revision: Union[str, Sequence[str], None] = '5027ff760272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lease_drivers_ibfk_2'), 'lease_drivers', type_='foreignkey')
    op.create_foreign_key(None, 'lease_drivers', 'drivers', ['driver_id'], ['driver_id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lease_drivers', type_='foreignkey')
    op.create_foreign_key(op.f('lease_drivers_ibfk_2'), 'lease_drivers', 'drivers', ['driver_id'], ['driver_id'])
    # ### end Alembic commands ###
