"""add is_required column in hackup_tasks table

Revision ID: 328d420128e9
Revises: 724940ce2af9
Create Date: 2025-11-01 11:27:20.103830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328d420128e9'
down_revision: Union[str, Sequence[str], None] = '724940ce2af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackup_tasks', sa.Column('is_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackup_tasks', 'is_required')
    # ### end Alembic commands ###
