"""hackup tasks and vehicle invoice number and date

Revision ID: c22bebe3dcdb
Revises: 087c6f11e9cc
Create Date: 2025-10-27 18:42:36.347577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c22bebe3dcdb'
down_revision: Union[str, Sequence[str], None] = '087c6f11e9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackup_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('drop_location', sa.String(length=255), nullable=True),
    sa.Column('drop_by', sa.String(length=255), nullable=True),
    sa.Column('drop_date', sa.Date(), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_task_done', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vehicle_hackups', sa.Column('paint_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('camera_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('partition_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('meter_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('rooftop_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('dmv_registration_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('tlc_inspection_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('dealership_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('bat_garage_task_id', sa.Integer(), nullable=True, comment='Foreign Key to HackUp Tasks table'))
    op.add_column('vehicle_hackups', sa.Column('is_insurance_procured', sa.Boolean(), nullable=True, comment='The insurance procured for the vehicle'))
    op.add_column('vehicle_hackups', sa.Column('insurance_number', sa.String(length=255), nullable=True, comment='Insurance number of the vehicle'))
    op.add_column('vehicle_hackups', sa.Column('insurance_start_date', sa.Date(), nullable=True, comment='Insurance start date of the vehicle'))
    op.add_column('vehicle_hackups', sa.Column('insurance_end_date', sa.Date(), nullable=True, comment='Insurance end date of the vehicle'))
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['dealership_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['paint_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['bat_garage_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['meter_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['rooftop_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['tlc_inspection_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['dmv_registration_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['partition_task_id'], ['id'])
    op.create_foreign_key(None, 'vehicle_hackups', 'hackup_tasks', ['camera_task_id'], ['id'])
    op.drop_column('vehicle_hackups', 'camera_to_location')
    op.drop_column('vehicle_hackups', 'meter_from_location')
    op.drop_column('vehicle_hackups', 'partition_type')
    op.drop_column('vehicle_hackups', 'rooftop_to_location')
    op.drop_column('vehicle_hackups', 'is_paint_completed')
    op.drop_column('vehicle_hackups', 'paint_to_location')
    op.drop_column('vehicle_hackups', 'partition_to_location')
    op.drop_column('vehicle_hackups', 'is_camera_installed')
    op.drop_column('vehicle_hackups', 'partition_status')
    op.drop_column('vehicle_hackups', 'is_partition_installed')
    op.drop_column('vehicle_hackups', 'meter_type')
    op.drop_column('vehicle_hackups', 'camera_status')
    op.drop_column('vehicle_hackups', 'paint_completed_date')
    op.drop_column('vehicle_hackups', 'paint_status')
    op.drop_column('vehicle_hackups', 'paint_from_location')
    op.drop_column('vehicle_hackups', 'rooftop_status')
    op.drop_column('vehicle_hackups', 'rooftop_from_location')
    op.drop_column('vehicle_hackups', 'partition_from_location')
    op.drop_column('vehicle_hackups', 'meter_to_location')
    op.drop_column('vehicle_hackups', 'partition_installed_date')
    op.drop_column('vehicle_hackups', 'rooftop_type')
    op.drop_column('vehicle_hackups', 'rooftop_installed_date')
    op.drop_column('vehicle_hackups', 'camera_type')
    op.drop_column('vehicle_hackups', 'partition_installed_charges')
    op.drop_column('vehicle_hackups', 'meter_installed_charges')
    op.drop_column('vehicle_hackups', 'paint_completed_charges')
    op.drop_column('vehicle_hackups', 'meter_status')
    op.drop_column('vehicle_hackups', 'is_rooftop_installed')
    op.drop_column('vehicle_hackups', 'camera_installed_charges')
    op.drop_column('vehicle_hackups', 'rooftop_installation_charges')
    op.drop_column('vehicle_hackups', 'meter_installed_date')
    op.drop_column('vehicle_hackups', 'camera_installed_date')
    op.drop_column('vehicle_hackups', 'camera_from_location')
    op.drop_column('vehicle_hackups', 'is_meter_installed')
    op.add_column('vehicles', sa.Column('invoice_number', sa.String(length=255), nullable=True, comment='Invoice number of the vehicle'))
    op.add_column('vehicles', sa.Column('invoice_date', sa.Date(), nullable=True, comment='Invoice date of the vehicle'))
    op.drop_column('vehicles', 'camera_type')
    op.drop_column('vehicles', 'delay_reason')
    op.drop_column('vehicles', 'dmv_registration_address')
    op.drop_column('vehicles', 'partition_type')
    op.drop_column('vehicles', 'metro_address')
    op.drop_column('vehicles', 'meter_type')
    op.drop_column('vehicles', 'paint_address')
    op.drop_column('vehicles', 'tlc_hackup_inspection_date')
    op.drop_column('vehicles', 'camera_address')
    op.drop_column('vehicles', 'rooftop_type')
    op.drop_column('vehicles', 'tlc_inspection_address')
    op.drop_column('vehicles', 'partition_address')
    op.drop_column('vehicles', 'rooftop_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('rooftop_address', mysql.VARCHAR(length=255), nullable=True, comment='Rooftop Address'))
    op.add_column('vehicles', sa.Column('partition_address', mysql.VARCHAR(length=255), nullable=True, comment='Partition Address'))
    op.add_column('vehicles', sa.Column('tlc_inspection_address', mysql.VARCHAR(length=255), nullable=True, comment='TLC Inspection Address'))
    op.add_column('vehicles', sa.Column('rooftop_type', mysql.VARCHAR(length=50), nullable=True, comment='Rooftop Type'))
    op.add_column('vehicles', sa.Column('camera_address', mysql.VARCHAR(length=255), nullable=True, comment='Camera Address'))
    op.add_column('vehicles', sa.Column('tlc_hackup_inspection_date', sa.DATE(), nullable=True, comment='TLC Hackup Inspection Date'))
    op.add_column('vehicles', sa.Column('paint_address', mysql.VARCHAR(length=255), nullable=True, comment='Paint Address'))
    op.add_column('vehicles', sa.Column('meter_type', mysql.VARCHAR(length=50), nullable=True, comment='Meter Type'))
    op.add_column('vehicles', sa.Column('metro_address', mysql.VARCHAR(length=255), nullable=True, comment='Metro Address'))
    op.add_column('vehicles', sa.Column('partition_type', mysql.VARCHAR(length=50), nullable=True, comment='Partition Type'))
    op.add_column('vehicles', sa.Column('dmv_registration_address', mysql.VARCHAR(length=255), nullable=True, comment='DMV Registration Address'))
    op.add_column('vehicles', sa.Column('delay_reason', mysql.TEXT(), nullable=True, comment='Delay Reason'))
    op.add_column('vehicles', sa.Column('camera_type', mysql.VARCHAR(length=50), nullable=True, comment='Camera Type'))
    op.drop_column('vehicles', 'invoice_date')
    op.drop_column('vehicles', 'invoice_number')
    op.add_column('vehicle_hackups', sa.Column('is_meter_installed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Has meter been installed'))
    op.add_column('vehicle_hackups', sa.Column('camera_from_location', mysql.VARCHAR(length=50), nullable=True, comment='Pickup location for camera'))
    op.add_column('vehicle_hackups', sa.Column('camera_installed_date', sa.DATE(), nullable=True, comment='Date when camera was installed'))
    op.add_column('vehicle_hackups', sa.Column('meter_installed_date', sa.DATE(), nullable=True, comment='Date when the meter was installed'))
    op.add_column('vehicle_hackups', sa.Column('rooftop_installation_charges', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Rooftop installation charges'))
    op.add_column('vehicle_hackups', sa.Column('camera_installed_charges', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Camera installation charges'))
    op.add_column('vehicle_hackups', sa.Column('is_rooftop_installed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Whether the rooftop is installed'))
    op.add_column('vehicle_hackups', sa.Column('meter_status', mysql.VARCHAR(length=50), nullable=True, comment='Meter Status'))
    op.add_column('vehicle_hackups', sa.Column('paint_completed_charges', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Paint completion charges'))
    op.add_column('vehicle_hackups', sa.Column('meter_installed_charges', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Meter installation charges'))
    op.add_column('vehicle_hackups', sa.Column('partition_installed_charges', mysql.INTEGER(), autoincrement=False, nullable=True, comment='partition installation charges'))
    op.add_column('vehicle_hackups', sa.Column('camera_type', mysql.VARCHAR(length=255), nullable=True, comment='Type of camera installed'))
    op.add_column('vehicle_hackups', sa.Column('rooftop_installed_date', sa.DATE(), nullable=True, comment='Date when the rooftop was installed'))
    op.add_column('vehicle_hackups', sa.Column('rooftop_type', mysql.VARCHAR(length=255), nullable=True, comment='Type of rooftop installed'))
    op.add_column('vehicle_hackups', sa.Column('partition_installed_date', sa.DATE(), nullable=True, comment='Date when partition was installed'))
    op.add_column('vehicle_hackups', sa.Column('meter_to_location', mysql.VARCHAR(length=50), nullable=True, comment='Drop location for meter'))
    op.add_column('vehicle_hackups', sa.Column('partition_from_location', mysql.VARCHAR(length=50), nullable=True, comment='Pickup location for partition'))
    op.add_column('vehicle_hackups', sa.Column('rooftop_from_location', mysql.VARCHAR(length=50), nullable=True, comment='Pickup location for rooftop'))
    op.add_column('vehicle_hackups', sa.Column('rooftop_status', mysql.VARCHAR(length=50), nullable=True, comment='meter Status'))
    op.add_column('vehicle_hackups', sa.Column('paint_from_location', mysql.VARCHAR(length=50), nullable=True, comment='Pickup location for paint'))
    op.add_column('vehicle_hackups', sa.Column('paint_status', mysql.VARCHAR(length=50), nullable=True, comment='Paint Status'))
    op.add_column('vehicle_hackups', sa.Column('paint_completed_date', sa.DATE(), nullable=True, comment='Date when paint was completed'))
    op.add_column('vehicle_hackups', sa.Column('camera_status', mysql.VARCHAR(length=50), nullable=True, comment='Camera Status'))
    op.add_column('vehicle_hackups', sa.Column('meter_type', mysql.VARCHAR(length=255), nullable=True, comment='Type of meter installed'))
    op.add_column('vehicle_hackups', sa.Column('is_partition_installed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Has partition got installed'))
    op.add_column('vehicle_hackups', sa.Column('partition_status', mysql.VARCHAR(length=50), nullable=True, comment='Partition Status'))
    op.add_column('vehicle_hackups', sa.Column('is_camera_installed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Has camera got installed'))
    op.add_column('vehicle_hackups', sa.Column('partition_to_location', mysql.VARCHAR(length=50), nullable=True, comment='Drop location for partition'))
    op.add_column('vehicle_hackups', sa.Column('paint_to_location', mysql.VARCHAR(length=50), nullable=True, comment='Drop location for paint'))
    op.add_column('vehicle_hackups', sa.Column('is_paint_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Has painting completed'))
    op.add_column('vehicle_hackups', sa.Column('rooftop_to_location', mysql.VARCHAR(length=50), nullable=True, comment='Drop location for rooftop'))
    op.add_column('vehicle_hackups', sa.Column('partition_type', mysql.VARCHAR(length=255), nullable=True, comment='Type of partition installed'))
    op.add_column('vehicle_hackups', sa.Column('meter_from_location', mysql.VARCHAR(length=50), nullable=True, comment='Pickup location for meter'))
    op.add_column('vehicle_hackups', sa.Column('camera_to_location', mysql.VARCHAR(length=50), nullable=True, comment='Drop location for camera'))
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_constraint(None, 'vehicle_hackups', type_='foreignkey')
    op.drop_column('vehicle_hackups', 'insurance_end_date')
    op.drop_column('vehicle_hackups', 'insurance_start_date')
    op.drop_column('vehicle_hackups', 'insurance_number')
    op.drop_column('vehicle_hackups', 'is_insurance_procured')
    op.drop_column('vehicle_hackups', 'bat_garage_task_id')
    op.drop_column('vehicle_hackups', 'dealership_task_id')
    op.drop_column('vehicle_hackups', 'tlc_inspection_task_id')
    op.drop_column('vehicle_hackups', 'dmv_registration_task_id')
    op.drop_column('vehicle_hackups', 'rooftop_task_id')
    op.drop_column('vehicle_hackups', 'meter_task_id')
    op.drop_column('vehicle_hackups', 'partition_task_id')
    op.drop_column('vehicle_hackups', 'camera_task_id')
    op.drop_column('vehicle_hackups', 'paint_task_id')
    op.drop_table('hackup_tasks')
    # ### end Alembic commands ###
